"""
Alembic environment for findata.

Responsibilities:

1. Read the database URL from the environment (``DATABASE_URL``), falling back
   to ``alembic.ini`` and then to a local SQLite file.
2. Import every ORM model so autogenerate can diff ``Base.metadata`` against
   the live schema.
3. Restrict autogenerate to the warehouse's own schemas, and collapse those
   schemas on SQLite (which has none).
4. Hide objects created by ``after_create`` event listeners, which autogenerate
   would otherwise try to drop.
"""

from __future__ import annotations

import logging
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

# ---------------------------------------------------------------------------
# Alembic Config object — gives access to values in alembic.ini
# ---------------------------------------------------------------------------
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# ---------------------------------------------------------------------------
# Import all models so that Base.metadata is fully populated
# ---------------------------------------------------------------------------
# findata.models.__init__ imports every model; the explicit names below exist so
# a missing model is a loud ImportError here rather than a silent DROP in an
# autogenerated migration.
from findata.models import Base  # noqa: E402
from findata.db.base import ALL_SCHEMAS, schema_translate_map_for  # noqa: E402
from findata.models import (  # noqa: E402, F401
    Article,
    ArticleSecurity,
    ArticleTransform,
    Company,
    DailyBar,
    Exchange,
    Insider,
)

target_metadata = Base.metadata

# ---------------------------------------------------------------------------
# Objects autogenerate must ignore
# ---------------------------------------------------------------------------
# Some DDL is emitted by SQLAlchemy ``after_create`` event listeners rather than
# declared on a model — see the dialect-conditional full-text search in
# findata/models/company.py. Autogenerate compares the database against
# Base.metadata, cannot find these there, reports them as "removed", and emits a
# DROP that would silently destroy the search index.
#
# ANY NEW EVENT-LISTENER DDL MUST BE ADDED HERE.
_EVENT_CREATED_OBJECTS: frozenset[str] = frozenset(
    {
        "ix_companies_description_fts",  # Postgres GIN index (company.py)
        "companies_fts",                 # SQLite FTS5 virtual table (company.py)
    }
)

#: SQLite builds shadow tables (``<name>_data``, ``_idx``, ``_docsize``,
#: ``_config``) behind every FTS5 virtual table. They are implementation detail
#: and must never reach a migration.
_FTS_SHADOW_PREFIXES: tuple[str, ...] = ("companies_fts_",)


def include_object(object, name, type_, reflected, compare_to) -> bool:  # noqa: A002
    """Return False for objects autogenerate should leave alone."""
    if name in _EVENT_CREATED_OBJECTS:
        return False
    if name and name.startswith(_FTS_SHADOW_PREFIXES):
        return False
    return True


def include_name(name, type_, parent_names) -> bool:
    """Restrict reflection to the warehouse's own schemas.

    With ``include_schemas=True``, autogenerate reflects *every* schema the
    connection can see — including ``information_schema`` and anything else
    living in the database. Without this filter it would propose dropping tables
    that are none of this project's business.

    ``None`` is the default schema, which holds ``alembic_version``.
    """
    if type_ == "schema":
        return name is None or name in ALL_SCHEMAS
    return True


# ---------------------------------------------------------------------------
# Database URL
# ---------------------------------------------------------------------------
def _get_url() -> str:
    """Return the database URL to use for migrations."""
    url = os.environ.get("DATABASE_URL")
    if url:
        return url
    ini_url = config.get_main_option("sqlalchemy.url")
    if ini_url and ini_url != "driver://user:pass@host/dbname":
        return ini_url
    return "sqlite:///resonance_desk.db"


def _configure_kwargs() -> dict:
    """Options shared by the offline and online paths."""
    return {
        "target_metadata": target_metadata,
        "render_as_batch": True,  # required for SQLite ALTER TABLE support
        "compare_type": True,
        "include_object": include_object,
        "include_name": include_name,
        "include_schemas": True,  # the warehouse spans reference/market/news
    }


# ---------------------------------------------------------------------------
# Offline migrations  (alembic upgrade head --sql)
# ---------------------------------------------------------------------------
def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to a database."""
    url = _get_url()
    context.configure(
        url=url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_configure_kwargs(),
    )

    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online migrations  (alembic upgrade head)
# ---------------------------------------------------------------------------
def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    url = _get_url()

    connectable = create_engine(url, poolclass=pool.NullPool)

    # SQLite has no schemas; collapse the logical ones the models declare so the
    # same migration script runs on both backends. Mirrors get_engine().
    translate_map = schema_translate_map_for(connectable.dialect.name)
    if translate_map:
        connectable = connectable.execution_options(schema_translate_map=translate_map)
        logger.debug("Applied schema_translate_map: %s", translate_map)

    with connectable.connect() as connection:
        context.configure(connection=connection, **_configure_kwargs())

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
